name: OneCreationRelease

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download artifact
        # You may pin to the exact commit or the version.
        # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # GitHub token
          github_token:  ${{ secrets.ONECREATION_PAT_TOKEN }}
          # Repository name with owner
          repo: One-Creation/oc-java-sdk
          # Artifact name (download all artifacts in not specified)
#           name: # optional
#           # Download latest artifact
#           latest: # optional
#           # Artifact unpack location
#           path: # optional, default is ./
