name: OneCreationRelease

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      releaseToBeClosed:
        description: 'Release number you want to close. i.e 1.0.20'
        # Input has to be provided for the workflow to run
        required: true  
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get JAva SDK Releases
      if: always()
      uses: robinraju/release-downloader@v1.6
      with:
        repository: One-Creation/oc-java-sdk
        tag: ${{  inputs.releaseToBeClosed  }}
        token: ${{ secrets.ONECREATION_PAT_TOKEN }}
        out-file-path: /tmp/releases

    - name: Get Python SDK Releases
      if: always()
      uses: robinraju/release-downloader@v1.6
      with:
        repository: One-Creation/oc-python-sdk
        tag: ${{  inputs.releaseToBeClosed  }}
        token: ${{ secrets.ONECREATION_PAT_TOKEN }}
        out-file-path: /tmp/releases

    - name: Get C++ SDK Releases
      if: always()
      uses: robinraju/release-downloader@v1.6
      with:
        repository: One-Creation/oc-cpp-sdk
        tag: ${{  inputs.releaseToBeClosed  }}
        token: ${{ secrets.ONECREATION_PAT_TOKEN }}
        out-file-path: /tmp/releases
        
    - name: Create Tag Release
      if: always()
      uses: beyond5959/create-release-github@v1
      env:
          GITHUB_TOKEN: ${{ secrets.ONECREATION_PAT_TOKEN }} # This token is provided by Actions, you do not need to create your own token        
      with:
        # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
        tag_name: ${{  inputs.releaseToBeClosed  }}
        # The name of the release. For example, `Release v1.0.1`
        release_name:  ${{  inputs.releaseToBeClosed  }}
        draft: true
        prerelease: true


    - name: Prepare Artifacts to Release
      if: always()    
      id: artifacts
      run: | 
        toRelease=$(echo "/tmp/releases/"$( dir . | sed 's/  / \/tmp\/releases\//g'))
        echo "toRelease=$toRelease" >> $GITHUB_OUTPUT 


    - name: Update Release
      if: always()    
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.ONECREATION_PAT_TOKEN }}
        # Paths to built files to be released. May be absolute or relative to \$\{\{ github.workspace \}\}.
        files: ${{ steps.artifacts.outputs.toRelease }}
        release:  ${{  inputs.releaseToBeClosed  }}
        tag: ${{  inputs.releaseToBeClosed  }}  
        # A one-line description for both the tag and the release.
        message: Test
        body: TEST RELEASE
        prerelease: false
        draft: false
                  



